apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: details
  namespace: heart
  labels:
    app: details
spec:
  serviceName: details  #
  replicas: 4
  selector:
    matchLabels:
      app: details

  template:
    metadata:
      labels:
        app: details
  
    spec:
      serviceAccountName: bookinfo-details    
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: details    
      containers:
      - name: details
        image: docker.io/istio/examples-bookinfo-details-v1:1.20.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "300m"
            memory: "300Mi"
          limits:
            cpu: "300m"
            memory: "300Mi"
        ports:
        - containerPort: 9080


