apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: productpage
  namespace: heart
  labels:
    app: productpage
spec:
  serviceName: productpage
  replicas: 5
  selector:
    matchLabels:
      app: productpage

  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
        prometheus.io/path: "/metrics"
      labels:
        app: productpage
  
    spec:
      serviceAccountName: bookinfo-productpage     
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: productpage     
      containers:
      - name: productpage
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.20.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "300m"
            memory: "300Mi"
          limits:
            cpu: "300m"
            memory: "300Mi"
        ports:
        - containerPort: 9080
