apiVersion: v1
kind: Service
metadata:
  name: frontend-pair
  namespace: pair
spec:
  selector:
    app: frontend-pair
  ports:
  - name: http
    port: 12001
    targetPort: 12001
  type: ClusterIP
  sessionAffinity: None    