apiVersion: v1
kind: Service
metadata:
  name: trigono
  namespace: pair
spec:
  selector:
    app: trigono
  ports:
    - name: http
      port: 12002
      targetPort: 12002
  type: ClusterIP
  sessionAffinity: None
