

apiVersion: apps/v1
kind: Deployment
metadata:
  name: downstream-worker1
  namespace: pair
  labels:
    app: downstream
    version: downstream-worker1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: downstream
      version: downstream-worker1

  template:
    metadata:
      labels:
        app: downstream
        version: downstream-worker1

    spec:
      containers:
      - name: downstream
        image: hokunpark/pair-benchmark:metrix-500
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1000m"
            memory: "2000Mi"
          limits:
            cpu: "1000m"
            memory: "2000Mi"  
        ports:
        - containerPort: 12001
        command: ["python"]
        args: ["metrix.py"]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker1

