apiVersion: v1
kind: Service
metadata:
  name: load-generator
  namespace: pair
spec:
  selector:
    app: load-generator
  ports:
  - name: http
    port: 12000
    targetPort: 12000
  type: ClusterIP
  sessionAffinity: None    