apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: bookinfo
  labels:
    app: ratings
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
      - name: ratings
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.20.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"  
        ports:
        - containerPort: 9080