apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: heart
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
  sessionAffinity: None  
  clusterIP: None    

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  namespace: heart
  labels:
    account: ratings