apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: heart
  labels:
    app: reviews
    service: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews
  sessionAffinity: None  
  clusterIP: None    


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  namespace: heart
  labels:
    account: reviews