apiVersion: v1
kind: Service
metadata:
  name: serviceb
  namespace: pair
spec:
  selector:
    app: serviceb
  ports:
    - name: http
      port: 11001
      targetPort: 11001
  type: ClusterIP
  sessionAffinity: None
