apiVersion: v1
kind: Service
metadata:
  name: servicea
  namespace: pair
spec:
  selector:
    app: servicea
  ports:
    - name: http
      port: 11000
      targetPort: 11000
  type: ClusterIP
  sessionAffinity: None
