apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-pair-dr
  namespace: pair
spec:
  host: frontend-pair
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
